package com.cfp.muaavin.ui;

import android.content.Intent;
import android.graphics.drawable.ColorDrawable;
import android.os.Bundle;
import android.app.Activity;
import android.support.v7.app.AppCompatActivity;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.webkit.WebView;
import android.widget.Button;

import com.cfp.muaavin.helper.PrefManager;

public class DisclaimerActivity extends AppCompatActivity {

    Button btnOk;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_disclaimer);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setHomeButtonEnabled(true);
        ColorDrawable colorDrawable = new ColorDrawable(getResources().getColor(R.color.appTheme)/*Color.parseColor("#3b5998")*/);
        getSupportActionBar().setBackgroundDrawable(colorDrawable);

        String htmlText = "<html><body style=\"text-align:justify\"> <font size=\"3\" color=\"#000000\" face=\"sans-serif\"> %s </font> </body></Html>";
        String aboutData = "The content posted, shared or otherwise generated by users in the Muavin community space doesn’t necessarily reflect or in any way express the views of Media Matters for Democracy or Code for Pakistan.<br>" +
                "Media Matters for Democracy and Code for Pakistan have utmost regard for user privacy and data protection. We want to ensure that Muavin is a safe space for community members. Any member, thus, found in violation of Muavin community standards will be immediately blocked." +
                "<br>" +
                "Please be advised that Muavin is still in the beta stage and we are trying our best to improve existing features and add more. Please share your feedback through our Facebook page.<br>" +
                "Please read through the Muavin community standards carefully before using the application.<br>";

        WebView viewAbout = (WebView) findViewById(R.id.webview);
        viewAbout.loadData(String.format(htmlText, aboutData), "text/html", "utf-8");
        viewAbout.setBackgroundColor(0);

        btnOk = (Button)findViewById(R.id.button3);
        btnOk.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                DisclaimerActivity.this.finish();
            }
        });
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.menu_web, menu);
        return true;
    }

    @Override
    public boolean onPrepareOptionsMenu(Menu menu) {
        return super.onPrepareOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                if (getFragmentManager().getBackStackEntryCount() > 0) {
                    getFragmentManager().popBackStack();
                } else super.onBackPressed();
                break;
            default:
                break;

        }
        return super.onOptionsItemSelected(item);
    }
}
